// <auto-generated />
using EfCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

//namespace EfCore.Migrations
//{
//    [DbContext(typeof(AppDBContext))]
//    partial class AppDBContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.25")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//            modelBuilder.Entity("EfCore.Models.Category", b =>
//                {
//                    b.Property<int>("CategoryId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

//                    b.Property<string>("CategoryName")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("CategoryId");

//                    b.ToTable("Categories");

//                    b.HasData(
//                        new
//                        {
//                            CategoryId = 1,
//                            CategoryName = "Electronics"
//                        },
//                        new
//                        {
//                            CategoryId = 2,
//                            CategoryName = "Home Appliance"
//                        },
//                        new
//                        {
//                            CategoryId = 3,
//                            CategoryName = "Cosmatics"
//                        });
//                });

//            modelBuilder.Entity("EfCore.Models.Product", b =>
//                {
//                    b.Property<int>("ProductId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

//                    b.Property<int>("CategoryId")
//                        .HasColumnType("int");

//                    b.Property<double>("Price")
//                        .HasColumnType("float");

//                    b.Property<string>("Title")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UrlImage")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("ProductId");

//                    b.HasIndex("CategoryId");

//                    b.ToTable("Products");
//                });

//            modelBuilder.Entity("EfCore.Models.Product", b =>
//                {
//                    b.HasOne("EfCore.Models.Category", "Category")
//                        .WithMany("Products")
//                        .HasForeignKey("CategoryId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Category");
//                });

//            modelBuilder.Entity("EfCore.Models.Category", b =>
//                {
//                    b.Navigation("Products");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
